version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installation des dépendances..."
      - npm ci

  pre_build:
    commands:
      - echo "Exécution des tests et du linting..."
      - npm run lint

  build:
    commands:
      - echo "Construction de l'application..."
      - npm run build

  post_build:
    commands:
      - echo "Construction terminée le $(date)"
      - echo "Préparation des fichiers pour le déploiement..."
      - aws s3 sync .next/static s3://${S3_BUCKET}/next/static/ --delete
      - aws s3 sync public/ s3://${S3_BUCKET}/ --delete
      - aws s3 sync .next/server s3://${S3_BUCKET}/server/ --delete
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"

artifacts:
  files:
    - ".next/**/*"
    - "public/**/*"
    - "package.json"
    - "next.config.mjs"
  discard-paths: no

cache:
  paths:
    - "node_modules/**/*"
    - ".next/cache/**/*"

env:
  variables:
    S3_BUCKET: ""
    CLOUDFRONT_DISTRIBUTION_ID: ""
  parameter-store:
    S3_BUCKET: "/rps/s3-bucket-name"
    CLOUDFRONT_DISTRIBUTION_ID: "/rps/cloudfront-distribution-id"
